//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaVisual.Idioma {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaVisual.Idioma.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        internal static string btnActividades {
            get {
                return ResourceManager.GetString("btnActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subir Foto.
        /// </summary>
        internal static string btnAgregarImagenPerfil {
            get {
                return ResourceManager.GetString("btnAgregarImagenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string btnCompartirGrupo {
            get {
                return ResourceManager.GetString("btnCompartirGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muro.
        /// </summary>
        internal static string btnCompartirMuro {
            get {
                return ResourceManager.GetString("btnCompartirMuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Evento.
        /// </summary>
        internal static string btnCrearEvento {
            get {
                return ResourceManager.GetString("btnCrearEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Grupo.
        /// </summary>
        internal static string btnCrearGrupo {
            get {
                return ResourceManager.GetString("btnCrearGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Mis Grupos.
        /// </summary>
        internal static string btnEliminarGrupo {
            get {
                return ResourceManager.GetString("btnEliminarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar Mis Eventos.
        /// </summary>
        internal static string btnEliminarMisEventos {
            get {
                return ResourceManager.GetString("btnEliminarMisEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        internal static string btnEventos {
            get {
                return ResourceManager.GetString("btnEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar Registro.
        /// </summary>
        internal static string btnFinalizarRegistro {
            get {
                return ResourceManager.GetString("btnFinalizarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos.
        /// </summary>
        internal static string btnGrupos {
            get {
                return ResourceManager.GetString("btnGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagen Video.
        /// </summary>
        internal static string btnImagenVideo {
            get {
                return ResourceManager.GetString("btnImagenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string btnInicio {
            get {
                return ResourceManager.GetString("btnInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string btnLink {
            get {
                return ResourceManager.GetString("btnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postear.
        /// </summary>
        internal static string btnPostear {
            get {
                return ResourceManager.GetString("btnPostear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        internal static string btnPrincipal {
            get {
                return ResourceManager.GetString("btnPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regristarse.
        /// </summary>
        internal static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguente.
        /// </summary>
        internal static string btnSiguiente2 {
            get {
                return ResourceManager.GetString("btnSiguiente2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenido.
        /// </summary>
        internal static string btnTipoContenido {
            get {
                return ResourceManager.GetString("btnTipoContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorar Grupos.
        /// </summary>
        internal static string btnVerMasGrupos {
            get {
                return ResourceManager.GetString("btnVerMasGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Mis Eventos.
        /// </summary>
        internal static string btnVerMisEventos {
            get {
                return ResourceManager.GetString("btnVerMisEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Mis Grupos.
        /// </summary>
        internal static string btnVerMisGrupos {
            get {
                return ResourceManager.GetString("btnVerMisGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volver.
        /// </summary>
        internal static string btnVolver2 {
            get {
                return ResourceManager.GetString("btnVolver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volver.
        /// </summary>
        internal static string btnVolverRegistroImg {
            get {
                return ResourceManager.GetString("btnVolverRegistroImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compartir en :.
        /// </summary>
        internal static string materialLabel1 {
            get {
                return ResourceManager.GetString("materialLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cual es tu pais de origen?.
        /// </summary>
        internal static string materialLabel2 {
            get {
                return ResourceManager.GetString("materialLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea tu muro.
        /// </summary>
        internal static string materialLabel4 {
            get {
                return ResourceManager.GetString("materialLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea una descripcion para tu muro, cuentanos algo sobre ti:.
        /// </summary>
        internal static string materialLabel5 {
            get {
                return ResourceManager.GetString("materialLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añade una imagen de portada para tu muro.
        /// </summary>
        internal static string materialLabel6 {
            get {
                return ResourceManager.GetString("materialLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desdeas que tu muro sea privado?.
        /// </summary>
        internal static string materialLabel7 {
            get {
                return ResourceManager.GetString("materialLabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        internal static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
    }
}
