//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaVisual.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapaVisual.Idioma.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividades.
        /// </summary>
        internal static string btnActividades {
            get {
                return ResourceManager.GetString("btnActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Foto.
        /// </summary>
        internal static string btnAgregarImagenPerfil {
            get {
                return ResourceManager.GetString("btnAgregarImagenPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        internal static string btnCompartirGrupo {
            get {
                return ResourceManager.GetString("btnCompartirGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muro.
        /// </summary>
        internal static string btnCompartirMuro {
            get {
                return ResourceManager.GetString("btnCompartirMuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Evento.
        /// </summary>
        internal static string btnCrearEvento {
            get {
                return ResourceManager.GetString("btnCrearEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Grupo.
        /// </summary>
        internal static string btnCrearGrupo {
            get {
                return ResourceManager.GetString("btnCrearGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Mis Grupos.
        /// </summary>
        internal static string btnEliminarGrupo {
            get {
                return ResourceManager.GetString("btnEliminarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Mis Eventos.
        /// </summary>
        internal static string btnEliminarMisEventos {
            get {
                return ResourceManager.GetString("btnEliminarMisEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos.
        /// </summary>
        internal static string btnEventos {
            get {
                return ResourceManager.GetString("btnEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalizar Registro.
        /// </summary>
        internal static string btnFinalizarRegistro {
            get {
                return ResourceManager.GetString("btnFinalizarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupos.
        /// </summary>
        internal static string btnGrupos {
            get {
                return ResourceManager.GetString("btnGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imagen Video.
        /// </summary>
        internal static string btnImagenVideo {
            get {
                return ResourceManager.GetString("btnImagenVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar.
        /// </summary>
        internal static string btnInicio {
            get {
                return ResourceManager.GetString("btnInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link.
        /// </summary>
        internal static string btnLink {
            get {
                return ResourceManager.GetString("btnLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string btnPincipal {
            get {
                return ResourceManager.GetString("btnPincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Postear.
        /// </summary>
        internal static string btnPostear {
            get {
                return ResourceManager.GetString("btnPostear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regristarse.
        /// </summary>
        internal static string btnRegistrarse {
            get {
                return ResourceManager.GetString("btnRegistrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguente.
        /// </summary>
        internal static string btnSiguiente2 {
            get {
                return ResourceManager.GetString("btnSiguiente2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido.
        /// </summary>
        internal static string btnTipoContenido {
            get {
                return ResourceManager.GetString("btnTipoContenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar Grupos.
        /// </summary>
        internal static string btnVerMasGrupos {
            get {
                return ResourceManager.GetString("btnVerMasGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Mis Eventos.
        /// </summary>
        internal static string btnVerMisEventos {
            get {
                return ResourceManager.GetString("btnVerMisEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Mis Grupos.
        /// </summary>
        internal static string btnVerMisGrupos {
            get {
                return ResourceManager.GetString("btnVerMisGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a volver.
        /// </summary>
        internal static string btnVolver2 {
            get {
                return ResourceManager.GetString("btnVolver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a volver.
        /// </summary>
        internal static string btnVolverRegistroImg {
            get {
                return ResourceManager.GetString("btnVolverRegistroImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir en :.
        /// </summary>
        internal static string materialLabel1 {
            get {
                return ResourceManager.GetString("materialLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cual es tu pais de origen?.
        /// </summary>
        internal static string materialLabel2 {
            get {
                return ResourceManager.GetString("materialLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea tu muro.
        /// </summary>
        internal static string materialLabel4 {
            get {
                return ResourceManager.GetString("materialLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una descripcion para tu muro, cuentanos algo sobre ti:.
        /// </summary>
        internal static string materialLabel5 {
            get {
                return ResourceManager.GetString("materialLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añade una imagen de portada para tu muro.
        /// </summary>
        internal static string materialLabel6 {
            get {
                return ResourceManager.GetString("materialLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desdeas que tu muro sea privado?.
        /// </summary>
        internal static string materialLabel7 {
            get {
                return ResourceManager.GetString("materialLabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string txtPassword {
            get {
                return ResourceManager.GetString("txtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string txtUsername {
            get {
                return ResourceManager.GetString("txtUsername", resourceCulture);
            }
        }
    }
}
